version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/eventdb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"  # Или "3000:80" ако користиш nginx
    depends_on:
      - backend

volumes:
  mongo-data:
