apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: event-planner-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: marijadimova25/event-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
      imagePullSecrets:
        - name: regcred
