apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: event-planner-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: marijadimova25/event-frontend:latest
          ports:
            - containerPort: 80

