name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: marijadimova25
      BACKEND_IMAGE: event-backend
      FRONTEND_IMAGE: event-frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image (multi-arch)
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}

    - name: Build and push frontend image (multi-arch)
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE }}:latest
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

  notify-on-failure:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Create issue on failure
      uses: peter-evans/create-issue@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "CI build failed for commit ${{ github.sha }}"
        body: |
          The CI/CD pipeline failed for commit ${{ github.sha }} on branch ${{ github.ref_name }}.

          Check the [workflow run logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
